name: docker_build_push_acr

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  docker_build_push_acr:
    name: 'Build docker containers and push to ACR'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
          
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Set semantic version number'
      run: echo "SEM_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: 'Build and push image'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          cwyfcr.azurecr.io/danger-dodgers:${{ github.sha }}
          cwyfcr.azurecr.io/danger-dodgers:${{ env.SEM_VERSION }}
        file: Dockerfile