---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.app.pvc.name . }}
  namespace: {{ .Release.Namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.app.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce